# Multitask Cat Classification Training Configuration (JSON-based)
# This configuration is for training a multitask model using JSON datasets

# Model Configuration
backbone: "mobilenet_v3_large" # Model architecture: mobilenet_v2, mobilenet_v3_small, mobilenet_v3_large
mode: "multitask" # Training mode: breed, emotion, multitask

# Training Parameters
batch_size: 32
learning_rate: 1e-3
weight_decay: 1e-4
epochs: 50
early_stopping: 10 # Patience for early stopping

# Optimizer configuration (config-file only, no CLI arguments)
optimizer: "adamư" # Options: "adam", "adamw", "sgd"

# Scheduler configuration (config-file only, no CLI arguments)
scheduler: "reduce_lr_on_plateau" # Options: "reduce_lr_on_plateau", "cosine", "step", "none"
# Parameters for ReduceLROnPlateau scheduler
scheduler_patience: 3
scheduler_factor: 0.2
scheduler_min_lr: 0.000001
# Parameters for StepLR scheduler
scheduler_step_size: 15
scheduler_gamma: 0.1
# Parameters for CosineAnnealingLR scheduler
scheduler_t_max: 20 # Number of epochs for a complete cosine cycle

# Model Parameters
img_size: 224
shared_features: false # Use shared features in multitask model

# Multitask Loss Weights
breed_weight: 1.0
emotion_weight: 1.0

# Data Configuration - JSON Datasets
train_json: "../data/json_multitask_datasets/test_dataset.json"
val_json: "../data/json_multitask_datasets/val_dataset.json"
test_json: "../data/json_multitask_datasets/test_dataset.json"
data_root: "../data/data-breed/processed" # Root directory for image paths in JSON

# Training Configuration
num_workers: 1
device: "cuda" # or "cpu"

# Logging and Checkpoints
checkpoint_dir: "checkpoints"
use_tensorboard: true
